name: AppImage Release

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml
    - run: flutter upgrade
    - run: flutter config --enable-linux-desktop
    - name: "Install dependencies"
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build build-essential pkg-config curl file git unzip xz-utils zip libgtk-3-dev
    - name: Build flutter app
      run: flutter build linux --release
    - name: Build AppImage unsing appimage-builder
      uses: docker://appimagecrafters/appimage-builder:latest
      with:
        entrypoint: appimage-builder
        args: --recipe ./AppImageBuilder.yml --skip-test
    - name: Save build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VisualizeChess-${{ github.ref_name }}-x86_64.AppImage
        path: './*.AppImage*'